### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by shad674** [mhuzaifa125/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
  - fix some of the lines that needed to be coded ✅
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
   - fix your headers ✅
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - Great job with the remote running instructions but we want to see the exact number of keystrokes it took to run the command remotely ✅
- [x] Text is formatted in a way that was easy for grader to read
   - fix some of the format. ✅

Additional comments from your grader:

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by mhuzaifa125** [comment]
@shad674 Hi I implemented the changes, can you please take another look?

**Comment by mhuzaifa125** [comment]
@jpolitz Hi can you help to take a look please?

**Comment by shad674** [comment]
Hi @mhuzaifa125, good job! I fixed your grade!

**Comment by mhuzaifa125** [comment]
Thanks!
